{"name": "Unsuccessful login", "status": "broken", "statusDetails": {"message": "NameError: name 'locator' is not defined", "trace": "index_page = <pages.index_page.IndexPage object at 0x000001B4C53E8950>, error_name = 'incorrect', error_password = 'incorrect', error_message = 'Epic sadface: Username and password do not match any user in this service'\n\n    @pytest.mark.api\n    @pytest.mark.smoke\n    @allure.description('Checking successful login with incorrect credentials')\n    @allure.label('owner', 'Vlad')\n    @allure.title('Unsuccessful login')\n    @allure.suite('Authorization suite')\n    @allure.severity(allure.severity_level.BLOCKER)\n    @pytest.mark.parametrize(\"error_name, error_password, error_message\", (case_1, case_2, case_3), ids=[\"Incorrect_password\", \"Empty_username\", \"Locked_out_user\"])\n    def test_unsuccessful_login(index_page, error_name, error_password, error_message):\n        index_page.enter_error_name(error_name)\n        index_page.enter_error_password(error_password)\n        index_page.click_to_login_button()\n>       index_page.validate_error(error_message)\n\ntests\\test_index_page.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\index_page.py:30: in validate_error\n    self.assertion(self.get_text(Locators.ERROR_MESSAGE), error_message)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.index_page.IndexPage object at 0x000001B4C53E8950>, actual = 'Epic sadface: Username and password do not match any user in this service'\nexpected = 'Epic sadface: Username and password do not match any user in this service'\n\n    def assertion(self, actual, expected):\n>       self.log.info(f\"{locator} comparing the expected result with the actual result\")\nE       NameError: name 'locator' is not defined\n\nbase_object\\base.py:36: NameError"}, "description": "Checking successful login with incorrect credentials", "steps": [{"name": "validate error name", "status": "passed", "parameters": [{"name": "error_name", "value": "'incorrect'"}], "start": 1679744942329, "stop": 1679744942417}, {"name": "validate error password", "status": "passed", "parameters": [{"name": "error_password", "value": "'incorrect'"}], "start": 1679744942417, "stop": 1679744942499}, {"name": "clicking to login button", "status": "passed", "start": 1679744942499, "stop": 1679744942564}, {"name": "validate error message", "status": "broken", "statusDetails": {"message": "NameError: name 'locator' is not defined\n", "trace": "  File \"C:\\Users\\Vlad\\PycharmProjects\\Saucedemo\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Vlad\\PycharmProjects\\Saucedemo\\pages\\index_page.py\", line 30, in validate_error\n    self.assertion(self.get_text(Locators.ERROR_MESSAGE), error_message)\n  File \"C:\\Users\\Vlad\\PycharmProjects\\Saucedemo\\base_object\\base.py\", line 36, in assertion\n    self.log.info(f\"{locator} comparing the expected result with the actual result\")\n                     ^^^^^^^\n"}, "parameters": [{"name": "error_message", "value": "'Epic sadface: Username and password do not match any user in this service'"}], "start": 1679744942564, "stop": 1679744942599}], "attachments": [{"name": "log", "source": "c813da6f-f24c-4cdf-aad7-69f0a134c2a7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "error_name", "value": "'incorrect'"}, {"name": "error_password", "value": "'incorrect'"}, {"name": "error_message", "value": "'Epic sadface: Username and password do not match any user in this service'"}], "start": 1679744942329, "stop": 1679744942599, "uuid": "2d559c9f-16f6-4fb9-9e0f-5888e3ed6e9e", "historyId": "9a7837802be43f64432b598f9ed30ef8", "testCaseId": "a7c18bc2d0a4e903f0cff3007abfbc12", "fullName": "tests.test_index_page#test_unsuccessful_login", "labels": [{"name": "suite", "value": "Authorization suite"}, {"name": "owner", "value": "Vlad"}, {"name": "severity", "value": "blocker"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "DESKTOP-SO90PSP"}, {"name": "thread", "value": "15892-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_index_page"}]}